name: Continuous Delivery

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        shell: bash
        run: pipx install poetry

      - name: Install FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master
      
      - name: Setup | Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      
      - name: Install Dependencies
        run: poetry install --with=dev

      - name: Run Tests with Pytest
        run: poetry run pytest

  release:
    needs: test
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Publish | Build and Publish to PyPi
        run: echo "Publishing to PyPi"