name: Continuous Integration

on:
  push:
    paths-ignore:
      - '*.md'
  
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10"]
        # os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        shell: bash
        run: pipx install poetry

      - name: Install FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master
      
      - name: Setup | Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      
      - name: Install Dependencies
        run: poetry install --with=dev

      - name: Run Tests with Pytest
        run: poetry run pytest